FROM postgres

ENV POSTGRES_PASSWORD=ThePassword

# default POSTGRES_USER for postgres image is "postgres"
#POSTGRES_USER=<custom user name>
# default db name for postgres image is to match $POSTGRES_USER
#POSTGRES_DB=<custom db name>

EXPOSE 5432